config/routes.rb
Rails.application.routes.draw do
  get 'members/new'
  get 'members/results'
  get 'members/index'
  get 'names/new'
  get 'names/results'
  get 'names/index'
  root 'members#new'
  post 'members/new'
  get 'members/ask'
  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/name.rb
class Name < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
def new
  @member = Member.new
end  
def index
	@members = Member.all
end
def destroy 
    @member = Member.find(params[:id])
    @members = Member.destroy(params[:id])
    redirect_to members_path
end
def prints
userinput = []
people = []
spouses = []
netpeople = []
gift = []
firstperson = []
firstperson = Member.pluck(:input)
secondperson = []
secondperson = Member.pluck(:spouse)
marriages = {}
marriages[firstperson] = secondperson
marriages = marriages.delete_if { |key, value| value.to_s.strip == '' }
	person = []
person = Member.pluck(:input)
persongift = []
persongift = Member.pluck(:gifttext)
spouse = []
spouse = Member.pluck(:spouse)
spousegift = []
spousegift = Member.pluck(:spousegift)
people = person + spouse
people = people.reject { |c| c.empty? }
gifts = persongift + spousegift
gifthash = {}
gifthash = Hash[people.zip gifts]
people = people.shuffle
originalshuffle = people
dataone = []
datatwo = []
backup = people
peoplelength = people.length
peopleuniqlength = people.uniq.length
i = peoplelength
u = peopleuniqlength
hashone = {}
myarray = []
itemonearray = []
itemtwoarray = []
if i % 2 == 0
	if people.uniq.length == people.length
		until i == 0 do
		itemone = people[0]
		dataone = dataone.push(itemone)
		hashone[itemone] = nil
		itemtwo = people[1]
		datatwo = datatwo.push(itemtwo)
		itemonearray = itemonearray.push(itemone)
		itemtwoarray = itemtwoarray.push(itemtwo)
		hashone[itemone] = itemtwo
			if marriages[itemone] != itemtwo && marriages[itemtwo] != itemone && itemonearray[-1] != marriages[itemtwo] && itemtwoarray[-1] != marriages[itemone]
				myvar = "#{itemone} is a match for #{itemtwo}. #{itemtwo} would like #{gifthash[itemtwo]}."
				myarray = myarray.push(myvar)
				people = people.drop(2)
				i -= 2
			else
				people = backup
				myarray = []
				itemonearray = []
				itemtwoarray = []
				i = peoplelength
				people = people.shuffle
				hashone = Hash.new
				dataone = []
				datatwo = []
			end
		end
backupdataone = dataone
backupdatatwo = datatwo
dataonelength = dataone.length
datatwolength = datatwo.length
x = dataonelength + datatwolength
mysecondarray = []
itemonearray = []
itemtwoarray = []
dataone = dataone.shuffle
datatwo = datatwo.shuffle
		until x == 0 do
itemone = datatwo[0]
itemtwo = dataone[0]
itemonearray = itemonearray.push(itemone)
itemtwoarray = itemtwoarray.push(itemtwo)
		if itemone != itemtwo && hashone[itemone] != hashone.values_at(itemone) && marriages[itemone] != itemtwo && marriages[itemtwo] != itemone && itemtwoarray[-1] != marriages[itemone] && itemonearray[-1] != marriages[itemtwo]

		myvar = "#{itemone} is a match for #{itemtwo}. #{itemtwo} would like #{gifthash[itemtwo]}."
		mysecondarray = mysecondarray.push(myvar)
		datatwo = datatwo.drop(1)
		x -= 1
		dataone = dataone.drop(1)
		x -= 1
		else
		itemonearray = []
		itemtwoarray = []
			dataone = backupdataone
			datatwo = backupdatatwo
			dataone = dataone.shuffle
			datatwo = datatwo.shuffle
			x = dataonelength + datatwolength
			mysecondarray = []
		end
		end
		finalarray = myarray + mysecondarray
	else
	finalarray = ["Duplicate name. Please try again.", ""]
	end
else
	finalarray = ["Please enter an even number of names.", ""]
end
return finalarray
end
def create
   @member = Member.new(member_params)
if @member.save
  redirect_to :action => 'ask'
else
  render :action => 'ask'
end
end
def ask
end
def show
end
def update
	@article = Member.find(params[:id])

	if @member.update(member_params)
		redirect_to @member
	else
		render 'edit'
		end
	end
def results
	@matches = prints
end
def member_params
      params.require(:member).permit(:input, :gifttext, :spouse, :spousegift)
end
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
def new
  @name = Name.new
end  
def index
	@names = Name.all
end
def show
end
def create
   @name = Name.new(name_params)
if @name.save
  redirect_to :action => 'new'
else
  render :action => 'new'
end
end
def results
end
    def name_params
      params.require(:name).permit(:input, :gifttext)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
def new
  @user = User.new
end  
def index
	@users = User.all
end

def create
    @user = User.new
if @user.save
  redirect_to "http://localhost:3000/user/new"
else
  render 'new'
end
end
def results
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sstwo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: @member, local: true ) do |f| %>
<p>Who is the participant?</p>
<div class="field">
    <%= f.label :person %>
    <%= f.text_field :input %>
</div>
<p>What gifts would they like?</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :gifttext %>
</div>
<p>Who, if anyone, is their spouse? If they don't have one you can leave this field blank</p>
<div class="field">
  <%= f.label :spouse %>
  <%= f.text_field :spouse %>
</div>
<p>What gifts would they like? If there is no spouse then you can leave this field blank.</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :spousegift %>
</div>
  <div class="action">
  <%= f.submit "Submit" %>
</div>
  <%= link_to 'Matches', members_results_path(@member) %>
<% end %>

app/views/members/ask.html.erb
<html>
<head></head>
<body>
<p>Are there more people?</p>
<%= link_to 'Yes', new_member_path %>/<%= link_to 'No', members_results_path %>

app/views/members/index.html.erb
 <div class="mydiv">
 <p>Index</p>
 <table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Gift</th>
      <th>Spouse</th>
      <th>Gift</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.input %></td>
        <td><%= member.gifttext %></td>
        <td><%= member.spouse %></td>
        <td><%= member.spousegift %></td>
      <td><%= button_to 'Destroy', member_path(member),
      method: :delete,
      data: {confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</tbody>
</table>
<%= link_to 'New', new_member_path %>
<%= link_to 'Matches', members_results_path %>
</div>

app/views/members/new.html.erb
<html>
<head>
	</head>
	<body>
<div class="mydiv">
<%= render 'form', member: @member %>
<%= link_to 'All Names', members_index_path %>
</div>
</body>
</html>

app/views/members/results.html.erb
<div class="mydiv">
<table>
	<tr>
		<th>Matches:</th>
	</tr>
		<% @matches.each do |results| %><br>
		<tr>
<td><%= results %></td>
<% end %>
</tr>
</table>
<br>
<%= link_to 'All names', members_index_path %>
<%= link_to 'New name', new_member_path %>
<div class="mydiv">

app/views/members/show.html.erb
<p>show</p>

app/views/names/_form.html.erb
<%= form_with(model: @member, local: true ) do |f| %>
<p>Who is the participant?</p>
<div class="field">
    <%= f.label :person %>
    <%= f.text_field :input %>
</div>
<p>What gifts would they like?</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :gifttext %>
</div>
<p>Who, if anyone, is their spouse? If they don't have one you can leave this field blank</p>
<div class="field">
  <%= f.label :spouse %>
  <%= f.text_field :spouse %>
</div>
<p>What gifts would they like? If there is no spouse then you can leave this field blank.</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :giftspouse %>
</div>
  <div class="actions">
  <%= f.submit "Submit" %>
</div>
  <%= link_to 'Done', names_results_path(@name) %>
<% end %>

app/views/names/index.html.erb
 <p>blah blah blah</p>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.input %></td>
        <td><%= member.gifttext %></td>
        <td><%= member.spouse %></td>
        <td><%= member.giftspouse %></td>
    </tr>
    <% end %>
</tbody>

app/views/names/new.html.erb
<%= render 'form', member: @member %>
<%= link_to 'index', names_index_path %>

app/views/names/results.html.erb
<h1>Names#results</h1>
<p>Find me in app/views/names/results.html.erb</p>

app/views/user/_form.html.erb
<%= form_with(model: user, local: true ) do |f| %>
<p>Who is the participant?</p>
<div class="field">
    <%= f.label :person %>
    <%= f.text_field :input %>
</div>
<p>What gifts would they like?</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :gifttext %>
</div>
<p>Who, if anyone, is their spouse? If they don't have one you can leave this field blank</p>
<div class="field">
  <%= f.label :person %>
  <%= f.text_field :input %>
</div>
<p>What gifts would they like? If there is no spouse then you can leave this field blank.</p>
<div class="field">
  <%= f.label :gifts %>
  <%= f.text_field :gifttext %>
</div>
  <div class="actions">
  <%= f.submit "Submit" %>
</div>
  <%= link_to 'Done', user_results_path(@user) %>
<% end %>

app/views/user/index.html.erb
 <p>blah blah blah</p>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.input %></td>
        <td><%= user.gifttext %></td>
    </tr>
    <% end %>
</tbody>

app/views/user/new.html.erb
<%= render 'form', user: @user %>

app/views/user/results.html.erb
<table>
  <thead>
    <tr>
      <th>Matches:
      </th>
    </tr>
  </thead>

<tbody><% prints.each do |results| %>
  <tr>
    <br><td><%= results %></td><br>
</tr>
<% end %>
</tbody></table>